# Generated by Django 5.0.1 on 2024-05-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0003_remove_setor_pasta"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="setores",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="cadastros.setor"
            ),
        ),
    ]
