# Generated by Django 5.0.6 on 2024-06-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_setores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
    ]
