# Generated by Django 5.0.6 on 2024-06-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='setores',
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('LEI', 'Leitor'), ('LID', 'Lider')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
