# Generated by Django 5.0.6 on 2024-09-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_staff_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('LEI', 'Leitor'), ('LID', 'Lider'), ('DIR', 'Diretor')], max_length=3),
        ),
    ]
