# Generated by Django 5.0.6 on 2024-10-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
