# Generated by Django 5.0.1 on 2024-05-29 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0002_setor_pasta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setor",
            name="pasta",
        ),
    ]
