# Generated by Django 5.0.6 on 2024-12-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_funcionario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
