# Generated by Django 5.0.6 on 2024-12-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_funcionario_excluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='areatrilha',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setor',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
