# Generated by Django 5.0.6 on 2024-06-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_area_id_areatrilha_id_funcionario_id_setor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
    ]
