# Generated by Django 5.0.6 on 2024-06-10 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_setor_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='setor',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_setor', to='cadastros.setor'),
            preserve_default=False,
        ),
    ]
