# Generated by Django 5.0.6 on 2024-06-21 13:24

import materiais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='arquivo_pdf',
            field=models.FileField(upload_to='livros/', validators=[materiais.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capa/', validators=[materiais.models.validate_file_type]),
        ),
    ]
