# Generated by Django 5.0.6 on 2024-06-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_livro_arquivo_pdf_alter_livro_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='descricao',
        ),
        migrations.AddField(
            model_name='livro',
            name='ano',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='linguagem',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
