# Generated by Django 5.0.6 on 2024-06-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_remove_livro_descricao_livro_ano_livro_linguagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='linguagem',
            new_name='idioma',
        ),
    ]
