# Generated by Django 4.2.13 on 2024-05-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos/')),
                ('fotos', models.FileField(blank=True, null=True, upload_to='fotos/')),
                ('pasta', models.ManyToManyField(max_length=100, related_name='material_pasta', to='materiais.pasta')),
            ],
        ),
    ]
