# Generated by Django 4.2.13 on 2024-05-22 22:16

from django.db import migrations, models
import materiais.models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiais'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='pasta',
        ),
        migrations.AddField(
            model_name='material',
            name='pastas',
            field=models.ManyToManyField(related_name='materiais', to='materiais.pasta'),
        ),
        migrations.AlterField(
            model_name='material',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/', validators=[materiais.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='material',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', validators=[materiais.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='material',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[materiais.models.validate_file_type]),
        ),
    ]
