# Generated by Django 5.0.6 on 2024-10-14 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('materiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoeficacia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pasta',
            name='area_trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta_areatrilha', to='cadastros.areatrilha'),
        ),
        migrations.AddField(
            model_name='pasta',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pasta',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, related_name='pastas_funcionarios', to='cadastros.funcionario'),
        ),
        migrations.AddField(
            model_name='pasta',
            name='setores',
            field=models.ManyToManyField(blank=True, related_name='pastas_setores', to='cadastros.setor'),
        ),
        migrations.AddField(
            model_name='material',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta_material', to='materiais.pasta'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.pasta'),
        ),
        migrations.AddField(
            model_name='avaliacaoeficacia',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.pasta'),
        ),
        migrations.AddField(
            model_name='respostaavaliacaoeficacia',
            name='avaliacao_eficacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.avaliacaoeficacia'),
        ),
        migrations.AddField(
            model_name='respostaavaliacaoeficacia',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visualizacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='cadastros.funcionario'),
        ),
        migrations.AddField(
            model_name='visualizacao',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='materiais.material'),
        ),
        migrations.AddField(
            model_name='visualizacao',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='materiais.pasta'),
        ),
    ]
