# Generated by Django 5.2.4 on 2025-09-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='arquivo_drive',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pasta',
            name='pasta_drive',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
