# Generated by Django 5.2.8 on 2025-11-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_material_arquivo_drive_pasta_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='visualizar_todos_arquivos_drive',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ArquivosDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_arquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.pasta')),
            ],
        ),
    ]
