# Generated by Django 5.0.1 on 2024-05-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materiais", "0003_material_created_at_material_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasta",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pasta",
            name="nome",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
