# Generated by Django 5.2.8 on 2025-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_pasta_carga_horaria_pasta_is_norma_regulamentadora_and_more'),
    ]

    operations = [
        
    ]
