# Generated by Django 5.2.8 on 2025-11-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_pasta_carga_horaria_pasta_is_norma_regulamentadora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='carga_horaria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pasta',
            name='is_norma_regulamentadora',
            field=models.BooleanField(default=False),
        ),
    ]
