# Generated by Django 5.0.1 on 2024-05-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0003_remove_setor_pasta"),
        ("materiais", "0005_remove_material_pastas_material_pasta"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasta",
            name="funcionarios",
            field=models.ManyToManyField(
                blank=True,
                related_name="pastas_funcionarios",
                to="cadastros.funcionario",
            ),
        ),
        migrations.AddField(
            model_name="pasta",
            name="setores",
            field=models.ManyToManyField(
                blank=True, related_name="pastas_setores", to="cadastros.setor"
            ),
        ),
    ]
