# Generated by Django 5.0.4 on 2024-05-31 20:45

import materiais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0007_remove_material_arquivo_remove_material_fotos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='material',
        ),
        migrations.RemoveField(
            model_name='video',
            name='material',
        ),
        migrations.AddField(
            model_name='material',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/', validators=[materiais.models.validate_file_type]),
        ),
        migrations.AddField(
            model_name='material',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/', validators=[materiais.models.validate_file_type]),
        ),
        migrations.AddField(
            model_name='material',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[materiais.models.validate_file_type]),
        ),
        migrations.DeleteModel(
            name='Arquivo',
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
