# Generated by Django 5.0.6 on 2024-06-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0009_material_video_youtube_visualizacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visualizacao',
        ),
    ]
