# Generated by Django 5.0.6 on 2024-06-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0010_delete_visualizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='video_youtube',
        ),
    ]
