# Generated by Django 5.0.6 on 2024-06-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_setor_pasta'),
        ('materiais', '0011_remove_material_video_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='video_youtube',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Visualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='cadastros.funcionario')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='materiais.material')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='materiais.pasta')),
            ],
        ),
    ]
