# Generated by Django 5.0.6 on 2024-06-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0012_material_video_youtube_visualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='video_youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
