# Generated by Django 5.0.6 on 2024-06-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0013_alter_material_video_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='video_youtube',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
