# Generated by Django 5.0.6 on 2024-09-26 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0018_respostaavaliacaoeficacia_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_finalizado', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_emissao_certificado', models.DateTimeField(auto_now_add=True)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.pasta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
