# Generated by Django 5.0.6 on 2024-10-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoprova',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta_name', to='materiais.pasta'),
        ),
        migrations.AddField(
            model_name='prova',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prova_pasta', to='materiais.pasta'),
        ),
        migrations.AddField(
            model_name='provarealizada',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.prova'),
        ),
    ]
