# Generated by Django 5.0.6 on 2024-06-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
