# Generated by Django 5.0.6 on 2024-10-14 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provarealizada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questao',
            name='prova',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questao_prova', to='avaliacoes.prova'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativa_questao', to='avaliacoes.questao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='alternativa_selecionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternativa_alternativa', to='avaliacoes.alternativa'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_resposta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resposta',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resposta_questao', to='avaliacoes.questao'),
        ),
        migrations.AlterUniqueTogether(
            name='provarealizada',
            unique_together={('usuario', 'prova')},
        ),
    ]
