# Generated by Django 5.0.6 on 2024-06-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0005_prova_corrigida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='corrigida',
            field=models.BooleanField(default=False),
        ),
    ]
