# Generated by Django 5.0.6 on 2024-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0006_alter_prova_corrigida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
