# Generated by Django 5.0.6 on 2024-06-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0007_alter_resposta_comentario_alter_resposta_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='corrigida',
            field=models.BooleanField(default=True),
        ),
    ]
