# Generated by Django 5.0.6 on 2024-06-19 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0008_alter_resposta_corrigida'),
    ]

    operations = [
        migrations.AddField(
            model_name='provarealizada',
            name='identificador_finalizado',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
