# Generated by Django 5.0.6 on 2024-06-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0009_provarealizada_identificador_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='corrigida',
        ),
    ]
