# Generated by Django 5.0.6 on 2024-06-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0011_prova_nota_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='prova_realizada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='avaliacoes.provarealizada'),
            preserve_default=False,
        ),
    ]
