# Generated by Django 5.0.6 on 2024-06-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0012_resposta_prova_realizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='prova_realizada',
        ),
    ]
