# Generated by Django 5.0.6 on 2024-08-12 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0014_historicoprova'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoprova',
            name='data_realizacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
