# Generated by Django 5.0.6 on 2024-08-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0016_alter_historicoprova_data_realizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoprova',
            name='data_realizacao',
        ),
    ]
