# Generated by Django 5.0.6 on 2024-08-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0020_alter_alternativa_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=255),
        ),
    ]
