# Generated by Django 5.0.6 on 2024-09-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0022_avaliacaoeficacia_respostaavaliacaoeficacia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostaavaliacaoeficacia',
            old_name='fk_avaliacao_eficacia',
            new_name='avaliacao_eficacia',
        ),
    ]
