# Generated by Django 5.0.6 on 2024-09-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0024_remove_respostaavaliacaoeficacia_avaliacao_eficacia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provarealizada',
            name='identificador_finalizado',
        ),
    ]
