# Generated by Django 4.2.13 on 2024-05-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='setor_area', to='cadastros.area')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('matricula', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('setor', models.ManyToManyField(related_name='funcionario_setor', to='cadastros.setor')),
            ],
        ),
    ]
