# Generated by Django 4.2.13 on 2024-05-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_alter_material_options_remove_material_pasta_and_more'),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='pasta',
            field=models.ManyToManyField(blank=True, related_name='setor_pasta', to='materiais.pasta'),
        ),
    ]
